from django.conf.urls import patterns, include, url
from django.contrib import admin
import sys
sys.path.append('..')
from db.views import *
urlpatterns = patterns('',
	url(r'^register$', register),
	url(r'^getuserphoto$', getuserphoto),
	url(r'^getphotobyemail$', getphotobyemail),
	url(r'^searchpostbyname$', SearchPostByName),
	url(r'^searchpost$', SearchPost),
        url(r'^forbidden$', Forbidden),
	url(r'^getunread$', GetUnread),
	url(r'^updatetimestamp$', UpdateTimestamp),
	url(r'^selectsubject$', SelectSubject),
	url(r'^deletesubject$', DeleteSubject),
	url(r'^userallsubject$', UserAllSubject),
	url(r'^getpermissions$', GetPermissions),
	url(r'^allsubject$', AllSubject),
	url(r'^subjectallpost$', SubjectAllPost),
	url(r'^postallfloor$',   PostAllFloor),
	url(r'^login$', login),
	url(r'^post$', Post),
	url(r'^replypost$', ReplyPost),
	url(r'^postchat$', PostChat),
	url(r'^getchat$', GetChat),
	url(r'^getalluser$', GetAllUser),
	url(r'^gettimestamp$', GetTimestamp),
	url(r'^addcontacts$', AddContacts),
	url(r'^haveread$', HaveRead),
	url(r'^inform$', Informed),
	url(r'^getcontacts$', GetContacts),
	url(r'^getunsolvedcontacts$', GetUnsolvedContacts),
	url(r'updatecontacts$', UpdateContacts),
	url(r'rejectcontacts$', RejectContacts),
	url(r'toppost$', TopPost),
	url(r'^essence$', EssencePost),
	url(r'removepost$', RemovePost),
	url(r'removecontact$', RejectContacts),
	url(r'updateprofile$', UpdateProfile),
	url(r'searchbyemail$', SearchByEmail),
	url(r'searchbyname$', SearchByName),
	url(r'getprofilebyname$', GetProfileByName),
	url(r'getprofilebyemail$', GetProfileByEmail),
	url(r'getessence$', GetEssence),
	url(r'selectcourse$', SelectCourse),
	url(r'^$', test),
)
